---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMHpOemc2ZWxkWFh5MHhkVE5tTW1sMmRISkNlRkpHZUVjPSIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
