---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
#  annotations:
#    ingress.alb.yc.io/subnets: 10.96.0.0/16
#    ingress.alb.yc.io/external-ipv4-address: 158.160.102.186
#    ingress.alb.yc.io/group-name: c497peak9bap37pu6s4t
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "devops-zimin.shop"
#      secretName: yc-certmgr-cert-id-fpqckhs7pjms4p5mt2vg
  rules:
    - host: "devops-zimin.shop"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080
        - path: /auth/whoami
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8081
        - path: /products
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8081
        - path: /categories
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8081